name = input("What is your name? :")
print("Hello " + name + "!")
age = input("please enter your age :")
print("okay " + name + " you are " + age + " years old! ")
print("Lets test my math skills")
num1 = input("Enter a number: ")
num2 = input("Enter another number: " )
print("Im going to Add " + num1 + " And " + num2 +  " together")
result = int(num1) + int(num2)
print(result)
answer = input("Is the answer stupid ass bitch ")
print(result)